version: '3.9'

services:
    sfcw_php:
        container_name: sfcw_php
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /usr/src/app
        tty: true
        volumes:
            - ./src:/usr/src/app/src